### ISSUE TITLE
Sorting for complex types does not work

### ISSUE THREAD

**Issue by cyberfish-dev** [rodrigopivi/odataUiGrid#3]
can you please make some changes in order to have working sorting stuff on complex types like 
innerObject.property

the issue is that it should generate something like 
?$orderby=innerObject/property%20desc&$top=7&$count=true

instead of 
?$orderby=innerObject.property%20desc&$top=7&$count=true

right now I cannot make field in ui-grid to be 'innerObject/property' because it will ruin all the logic. can you just replace dot with '/' on line 166 to be 

odataQueryOptions.$currentQuery.sort = sortCol.field.replace('.','/'); (maybe with some null check not to get undef exception..)

**Comment by rodrigopivi** [comment]
Sounds reasonable, i'll try to get some time soon, if you can, you are also welcome to submit a PR

**Comment by rodrigopivi** [comment]
https://github.com/rodrigopivi/odataUiGrid/commit/23f5d072605ef562e0688a2ce66bfa6413d7f93e
